version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: payment-postgres
    restart: always
    environment:
      POSTGRES_DB: paymentdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: payment-backend
    restart: always
    ports:
      - "3001:3000"
    environment:
      DB_HOST: postgres
      DB_NAME: paymentdb
      DB_USER: postgres
      DB_PASSWORD: postgres
      PORT: 3000
    depends_on:
      - postgres

volumes:
  postgres_data:
